# Generated by Django 3.0.6 on 2020-05-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('handle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('tweet_id', models.CharField(max_length=200, unique=True)),
                ('tweet_text', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('has_data', models.BooleanField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Paper')),
            ],
        ),
    ]
